"""公共契约包——SceneWeave 接口的唯一来源（PRD 第 8 节）。

后端请求／响应模型在此定义，并由 OpenAPI 导出前端类型。本包**不得**导入
领域实现、具体模型客户端或任何外部分析包。
"""

from __future__ import annotations

from .action import ActionDraft, ActionRecord
from .analysis import (
    AnalysisCapability,
    AnalysisMaterialRef,
    AnalysisReport,
    AnalysisRequest,
)
from .api_analysis import (
    AnalysisCapabilityView,
    AnalysisCreateRequest,
    AnalysisListView,
    AnalysisRecordView,
)
from .api import (
    AgentCreateRequest,
    AgentRenameRequest,
    AgentSpecRequest,
    PresetListView,
    PresetSceneCreateRequest,
    PresetSummaryView,
    SceneCreateRequest,
    SceneDetailView,
    SceneListView,
    SceneSummaryView,
    TemplateCopyRequest,
    TemplateCreateRequest,
    TemplateListView,
    TemplateUpdateRequest,
)
from .common import (
    CONTRACT_ENUMS,
    CONTRACT_LIMIT_CODEPOINTS,
    EXTERNAL_PORTS,
    ApiError,
    ContractSummary,
    EnumSummary,
    HealthResponse,
    build_contract_summary,
)
from .enums import (
    ActionType,
    AnalysisStatus,
    ControlCommandType,
    EventStatus,
    EventVisibility,
    ModelFailureKind,
    PauseReason,
    RunState,
    SchedulerReason,
    TurnStatus,
)
from .event import Event, EventSubmission
from .ids import (
    ActionId,
    AnalysisId,
    AgentId,
    AttemptId,
    EventId,
    MessageId,
    RequestId,
    SceneId,
    TemplateId,
    TurnId,
)
from .limits import (
    APP_NAME,
    APP_VERSION,
    CONTRACT_VERSION,
    DEFAULT_AGENTS_PER_SCENE,
    DEFAULT_MODEL_NAME,
    MAX_AGENTS_PER_SCENE,
    MAX_AGENT_NAME_CODEPOINTS,
    MAX_ANALYSIS_BEHAVIOR_DESCRIPTION_CODEPOINTS,
    MAX_ANALYSIS_CONTEXT_CODEPOINTS,
    MAX_ANALYSIS_REQUESTS_PER_SCENE,
    MAX_EVENT_BODY_CODEPOINTS,
    MAX_INITIAL_GOAL_CODEPOINTS,
    MAX_PERSONA_CODEPOINTS,
    MAX_PRIVATE_BACKGROUND_CODEPOINTS,
    MAX_PROMPT_CHARS,
    MAX_ROLE_REQUESTS_PER_SCENE,
    MAX_SCENE_BACKGROUND_CODEPOINTS,
    MAX_SCENE_REQUEST_LIMIT,
    MAX_SPEAK_TEXT_CODEPOINTS,
    MAX_SPEECH_STYLE_CODEPOINTS,
    MIN_AGENTS_PER_SCENE,
    MIN_SCENE_REQUEST_LIMIT,
    MIN_SPEAK_TEXT_CODEPOINTS,
    SCHEMA_VERSION,
    codepoint_length,
)
from .model import (
    ModelActionRequest,
    ModelActionResponse,
    ModelFailure,
    ModelParams,
    ReferenceScope,
    Usage,
)
from .registry import CONTRACT_MODELS, contract_json_schemas
from .runtime import (
    CommandAck,
    ControlCommand,
    InjectEventCommand,
    RoleCursor,
    RunStatus,
    SchedulerDirective,
    TimelineEntry,
)
from .scene import (
    AgentProfileFields,
    AgentSnapshot,
    AgentTemplate,
    Budget,
    BudgetUsage,
    Message,
    Scene,
    SceneAgent,
    validate_agent_count,
)

__all__ = [
    # ids
    "ActionId",
    "AnalysisId",
    "AgentId",
    "AttemptId",
    "EventId",
    "MessageId",
    "RequestId",
    "SceneId",
    "TemplateId",
    "TurnId",
    # M06 API 契约
    "AnalysisCapabilityView",
    "AnalysisCreateRequest",
    "AnalysisListView",
    "AnalysisRecordView",
    # M01 API 契约
    "AgentCreateRequest",
    "AgentRenameRequest",
    "AgentSpecRequest",
    "PresetListView",
    "PresetSceneCreateRequest",
    "PresetSummaryView",
    "SceneCreateRequest",
    "SceneDetailView",
    "SceneListView",
    "SceneSummaryView",
    "TemplateCopyRequest",
    "TemplateCreateRequest",
    "TemplateListView",
    "TemplateUpdateRequest",
    # limits / version
    "APP_NAME",
    "APP_VERSION",
    "CONTRACT_VERSION",
    "SCHEMA_VERSION",
    "DEFAULT_AGENTS_PER_SCENE",
    "DEFAULT_MODEL_NAME",
    "MAX_AGENTS_PER_SCENE",
    "MAX_AGENT_NAME_CODEPOINTS",
    "MAX_ANALYSIS_BEHAVIOR_DESCRIPTION_CODEPOINTS",
    "MAX_ANALYSIS_CONTEXT_CODEPOINTS",
    "MAX_ANALYSIS_REQUESTS_PER_SCENE",
    "MAX_EVENT_BODY_CODEPOINTS",
    "MAX_INITIAL_GOAL_CODEPOINTS",
    "MAX_PERSONA_CODEPOINTS",
    "MAX_PRIVATE_BACKGROUND_CODEPOINTS",
    "MAX_PROMPT_CHARS",
    "MAX_ROLE_REQUESTS_PER_SCENE",
    "MAX_SCENE_BACKGROUND_CODEPOINTS",
    "MAX_SCENE_REQUEST_LIMIT",
    "MAX_SPEAK_TEXT_CODEPOINTS",
    "MAX_SPEECH_STYLE_CODEPOINTS",
    "MIN_AGENTS_PER_SCENE",
    "MIN_SCENE_REQUEST_LIMIT",
    "MIN_SPEAK_TEXT_CODEPOINTS",
    "codepoint_length",
    # enums
    "ActionType",
    "AnalysisStatus",
    "ControlCommandType",
    "EventStatus",
    "EventVisibility",
    "ModelFailureKind",
    "PauseReason",
    "RunState",
    "SchedulerReason",
    "TurnStatus",
    # action
    "ActionDraft",
    "ActionRecord",
    # event
    "Event",
    "EventSubmission",
    # scene
    "AgentProfileFields",
    "AgentSnapshot",
    "AgentTemplate",
    "Budget",
    "BudgetUsage",
    "Message",
    "Scene",
    "SceneAgent",
    "validate_agent_count",
    # runtime
    "CommandAck",
    "ControlCommand",
    "InjectEventCommand",
    "RoleCursor",
    "RunStatus",
    "SchedulerDirective",
    "TimelineEntry",
    # model port
    "ModelActionRequest",
    "ModelActionResponse",
    "ModelFailure",
    "ModelParams",
    "ReferenceScope",
    "Usage",
    # analysis port
    "AnalysisCapability",
    "AnalysisMaterialRef",
    "AnalysisReport",
    "AnalysisRequest",
    # common
    "ApiError",
    "CONTRACT_ENUMS",
    "CONTRACT_LIMIT_CODEPOINTS",
    "CONTRACT_MODELS",
    "ContractSummary",
    "EXTERNAL_PORTS",
    "EnumSummary",
    "HealthResponse",
    "build_contract_summary",
    "contract_json_schemas",
]
